### PR TITLE
Ensure DerivativesManager deletes temporary directory; closes #454

### LINKED ISSUE #454: DerivativesManager should ensure the temporary directory is deleted
DerivativesManager#generate_derivative! should ensure that the temporary directory is removed even if an exception is thrown in the method body.

### PR DESCRIPTION
**Pull request by coblej**

### CODE REVIEW

File: spec/managers/derivatives_manager_spec.rb [hunk 1]
```diff
@@ -120,6 +120,17 @@ class MultiresImageable < ContentBearing
...
       end
 
+      describe "exception during derivative generation" do
+        let(:object) { ContentBearing.create }
+        before do
+          allow(Dir::Tmpname).to receive(:make_tmpname).with('', nil) { 'test-temp-dir' }
+        end
+        it "should delete the temporary work directory" do
+          expect { object.derivatives.generate_derivative!(Ddr::Derivatives::DERIVATIVES[:thumbnail]) }.to raise_error
+          expect(File.exist?(File.join(Dir.tmpdir, 'test-temp-dir'))).to be_falsey
```
Comment (dchandekstark) [inline spec/managers/derivatives_manager_spec.rb]: I wouldn't think you'd need `be_falsey` here.

File: spec/managers/derivatives_manager_spec.rb [hunk 2]
```diff
@@ -120,6 +120,17 @@ class MultiresImageable < ContentBearing
         end
       end
 
+      describe "exception during derivative generation" do
+        let(:object) { ContentBearing.create }
+        before do
+          allow(Dir::Tmpname).to receive(:make_tmpname).with('', nil) { 'test-temp-dir' }
+        end
+        it "should delete the temporary work directory" do
+          expect { object.derivatives.generate_derivative!(Ddr::Derivatives::DERIVATIVES[:thumbnail]) }.to raise_error
```
Comment (dchandekstark) [inline spec/managers/derivatives_manager_spec.rb]: Please specify exception class with `.to raise_error`.

**Comment by coblej** [comment]
@dchandekstark Refactored as we discussed and ready for your review
