### PR TITLE
Decoupled Ddr::Events::Event from Ddr::Auth::User

### LINKED ISSUE #235: Remove Blacklight::User from Ddr::Auth::User
We don't want Blacklight used explicitly in ddr-models.

### LINKED ISSUE #263: Increase size of Event exception field or truncate input

### LINKED ISSUE #277: Deprecate #user_id= for events

### PR DESCRIPTION
**Pull request by dchandekstark**
Closes #277
Added migration to change event exception field to text - fixes #263
Removed Blacklight::User from Ddr::Auth::User - closes #235

### CODE REVIEW

File: db/migrate/20150710211530_change_events_exception_to_text.rb [hunk 1]
```diff
@@ -0,0 +1,9 @@
+class ChangeEventsExceptionToText < ActiveRecord::Migration
+  def up
+    change_column :events, :exception, :text
```
Comment (coblej) [inline db/migrate/20150710211530_change_events_exception_to_text.rb]: @dchandekstark Consider adding `, limit: 65535` (or some such number) to this line.  Otherwise, in certain contexts at least, the limit may end up set too low in the resulting schema.  See, for example, line 28 in spec/dummy/db/schema,rb below, where it is set to 255.

Comment (dchandekstark) [inline db/migrate/20150710211530_change_events_exception_to_text.rb]: @coblej Good catch! I didn't even look at the schema and had forgotten about that.
